version: '1.0'

#Data pipeline parameters
database:
  name: 'OHLC.db'
  ticker: 'GME'
  start_date: '2022-08-01'
  end_date: '2022-08-02'
  freq: 'C'

#Screener parameters
screener:
  return_threshold: 0.01
  recurrence_threshold: 0.6

#Forecast parameters
forecast:
  training_period: 720 #Correlative days starting at 'training period' + 'test_period' period from today
  test_period: 100 #Correlative days forecasted from last day of 'training period'
  continuous:
    model: 'armina'
    fh: 1
    fold: 1
    system_log: False
  discrete:
    fh: 1
    fold: 1
    system_log: False
  save_name: 'forecast_model'

#Backtesting parameters
backtesting:
  threshold: 0.01
  commission: 1 #Absolute amount
  start_date: None
  end_date: None
  initial_cash: 10000

